services:
  - type: web
    name: gasbuddy-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT gas_price_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: FLASK_ENV
        value: production
